# graphs += $(call graph,u,3,1).el
# graphs += $(call graph,u,3,1).al
# graphs += $(call graph,u,3,1).mtx
graphs += $(call graph,u,7,1).al
graphs += $(call graph,u,7,1).el
graphs += $(call graph,u,7,1).mtx
# graphs += $(call graph,u,7,8).al
# graphs += $(call graph,u,7,8).el
# graphs += $(call graph,u,7,8).mtx
# graphs += $(call graph,u,7,16).al
# graphs += $(call graph,u,7,16).el
# graphs += $(call graph,u,7,16).mtx
# graphs += $(call graph,u,7,32).al
# graphs += $(call graph,u,7,32).el
# graphs += $(call graph,u,7,32).mtx
graphs += $(call graph,u,10,1).al
graphs += $(call graph,u,10,1).el
graphs += $(call graph,u,10,1).mtx
graphs += $(call graph,u,10,2).al
graphs += $(call graph,u,10,2).el
graphs += $(call graph,u,10,2).mtx
graphs += $(call graph,u,10,3).al
graphs += $(call graph,u,10,3).el
graphs += $(call graph,u,10,3).mtx
graphs += $(call graph,u,10,4).al
graphs += $(call graph,u,10,4).el
graphs += $(call graph,u,10,4).mtx
# graphs += $(call graph,u,10,8).al
# graphs += $(call graph,u,10,8).el
# graphs += $(call graph,u,10,8).mtx
# graphs += $(call graph,u,10,16).al
# graphs += $(call graph,u,10,16).el
# graphs += $(call graph,u,10,16).mtx
# graphs += $(call graph,u,10,32).al
# graphs += $(call graph,u,10,32).el
# graphs += $(call graph,u,10,32).mtx
# graphs += $(call graph,u,11,8).al
# graphs += $(call graph,u,11,8).el
# graphs += $(call graph,u,11,8).mtx
# graphs += $(call graph,u,11,16).al
# graphs += $(call graph,u,11,16).el
# graphs += $(call graph,u,11,16).mtx
# graphs += $(call graph,u,11,32).al
# graphs += $(call graph,u,11,32).el
# graphs += $(call graph,u,11,32).mtx
# graphs += $(call graph,u,16,8).al
# graphs += $(call graph,u,16,8).el
# graphs += $(call graph,u,16,8).mtx
# graphs += $(call graph,u,16,16).al
# graphs += $(call graph,u,16,16).el
# graphs += $(call graph,u,16,16).mtx
# graphs += $(call graph,u,16,32).al
# graphs += $(call graph,u,16,32).el
# graphs += $(call graph,u,16,32).mtx
graphs += $(call graph,u,20,1).al
graphs += $(call graph,u,20,1).el
graphs += $(call graph,u,20,1).mtx
graphs += $(call graph,u,20,2).al
graphs += $(call graph,u,20,2).el
graphs += $(call graph,u,20,2).mtx
graphs += $(call graph,u,20,4).al
graphs += $(call graph,u,20,4).el
graphs += $(call graph,u,20,4).mtx
graphs += $(call graph,u,20,8).al
graphs += $(call graph,u,20,8).el
graphs += $(call graph,u,20,8).mtx
graphs += $(call graph,g,20,1).al
graphs += $(call graph,g,20,1).el
graphs += $(call graph,g,20,1).mtx
graphs += $(call graph,g,20,2).al
graphs += $(call graph,g,20,2).el
graphs += $(call graph,g,20,2).mtx
graphs += $(call graph,g,20,4).al
graphs += $(call graph,g,20,4).el
graphs += $(call graph,g,20,4).mtx
graphs += $(call graph,g,20,8).al
graphs += $(call graph,g,20,8).el
graphs += $(call graph,g,20,8).mtx
# graphs += $(call graph,u,20,16).al
# graphs += $(call graph,u,20,16).el
# graphs += $(call graph,u,20,16).mtx
# graphs += $(call graph,u,20,32).al
# graphs += $(call graph,u,20,32).el
# graphs += $(call graph,u,20,32).mtx
# graphs += $(call graph,g,7,8).al
# graphs += $(call graph,g,7,8).el
# graphs += $(call graph,g,7,8).mtx
# graphs += $(call graph,g,7,16).al
# graphs += $(call graph,g,7,16).el
# graphs += $(call graph,g,7,16).mtx
# graphs += $(call graph,g,7,32).al
# graphs += $(call graph,g,7,32).el
# graphs += $(call graph,g,7,32).mtx
# graphs += $(call graph,g,10,8).al
# graphs += $(call graph,g,10,8).el
# graphs += $(call graph,g,10,8).mtx
# graphs += $(call graph,g,10,16).al
# graphs += $(call graph,g,10,16).el
# graphs += $(call graph,g,10,16).mtx
# graphs += $(call graph,g,10,32).al
# graphs += $(call graph,g,10,32).el
# graphs += $(call graph,g,10,32).mtx
# graphs += $(call graph,g,11,8).al
# graphs += $(call graph,g,11,8).el
# graphs += $(call graph,g,11,8).mtx
# graphs += $(call graph,g,11,16).al
# graphs += $(call graph,g,11,16).el
# graphs += $(call graph,g,11,16).mtx
# graphs += $(call graph,g,11,32).al
# graphs += $(call graph,g,11,32).el
# graphs += $(call graph,g,11,32).mtx
# graphs += $(call graph,g,16,8).al
# graphs += $(call graph,g,16,8).el
# graphs += $(call graph,g,16,8).mtx
# graphs += $(call graph,g,16,16).al
# graphs += $(call graph,g,16,16).el
# graphs += $(call graph,g,16,16).mtx
# graphs += $(call graph,g,16,32).al
# graphs += $(call graph,g,16,32).el
# graphs += $(call graph,g,16,32).mtx
# graphs += $(call graph,g,20,8).al
# graphs += $(call graph,g,20,8).el
# graphs += $(call graph,g,20,8).mtx
# graphs += $(call graph,g,20,16).al
# graphs += $(call graph,g,20,16).el
# graphs += $(call graph,g,20,16).mtx
# graphs += $(call graph,g,20,32).al
# graphs += $(call graph,g,20,32).el
# graphs += $(call graph,g,20,32).mtx
# graphs += $(call graph,z,7,8).al
# graphs += $(call graph,z,7,8).el
# graphs += $(call graph,z,7,8).mtx
# graphs += $(call graph,z,7,16).al
# graphs += $(call graph,z,7,16).el
# graphs += $(call graph,z,7,16).mtx
# graphs += $(call graph,z,7,32).al
# graphs += $(call graph,z,7,32).el
# graphs += $(call graph,z,7,32).mtx
# graphs += $(call graph,z,10,8).al
# graphs += $(call graph,z,10,8).el
# graphs += $(call graph,z,10,8).mtx
# graphs += $(call graph,z,10,16).al
# graphs += $(call graph,z,10,16).el
# graphs += $(call graph,z,10,16).mtx
# graphs += $(call graph,z,10,32).al
# graphs += $(call graph,z,10,32).el
# graphs += $(call graph,z,10,32).mtx
# graphs += $(call graph,z,11,8).al
# graphs += $(call graph,z,11,8).el
# graphs += $(call graph,z,11,8).mtx
# graphs += $(call graph,z,11,16).al
# graphs += $(call graph,z,11,16).el
# graphs += $(call graph,z,11,16).mtx
# graphs += $(call graph,z,11,32).al
# graphs += $(call graph,z,11,32).el
# graphs += $(call graph,z,11,32).mtx
# graphs += $(call graph,z,16,8).al
# graphs += $(call graph,z,16,8).el
# graphs += $(call graph,z,16,8).mtx
# graphs += $(call graph,z,16,16).al
# graphs += $(call graph,z,16,16).el
# graphs += $(call graph,z,16,16).mtx
# graphs += $(call graph,z,16,32).al
# graphs += $(call graph,z,16,32).el
# graphs += $(call graph,z,16,32).mtx
# graphs += $(call graph,z,20,8).al
# graphs += $(call graph,z,20,8).el
# graphs += $(call graph,z,20,8).mtx
# graphs += $(call graph,z,20,16).al
# graphs += $(call graph,z,20,16).el
# graphs += $(call graph,z,20,16).mtx
# graphs += $(call graph,z,20,32).al
# graphs += $(call graph,z,20,32).el
# graphs += $(call graph,z,20,32).mtx
